posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, \
    like_unlike_post, PostDeleteView, PostUpdateView
from .feeds import LatestPostsFeed

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view,
    invites_received_view,
    invite_profile_list_view,
    ProfileListView,
    ProfileDetailView,
    send_invitation,
    remove_from_friends,
    accept_invitation,
    reject_invitation,
    search_from_friends,
)

app_name = 'profiles'
urlpatterns = [
    path('userprofile/', my_profile_view, name='my-profile'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('to-invite/', invite_profile_list_view, name='invite-profile-view'),
    path('send-invite/', send_invitation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('search-for-friends/', search_from_friends, name='search-for-friends'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),

    path('my-invite/accept/', accept_invitation, name='accept-invite'),
    path('my-invite/reject/', reject_invitation, name='reject-invite'),
]

soro_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .view import home_view

urlpatterns = [

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profiles/models.py
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse

from .utils import get_randomcode
from django.template.defaultfilters import slugify
from django.db.models import Q


# Create your models here.
class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        print(qs)

        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
        print(accepted)

        available = [profile for profile in profiles if profile not in accepted]
        print(available)
        return available

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles


class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="No Bio...", max_length=300)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    avatar = CloudinaryField('post', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], blank=True)
    # install pillow
    # create media_root
    # find avatar.png
    friends = models.ManyToManyField(User, blank=True, related_name='friend')
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

    def get_absolute_url(self):
        return reverse("profiles:profile-detail-view", kwargs={"slug": self.slug})

    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()

    def get_posts_no(self):
        return self.posts.all().count()

    def get_all_authors_posts(self):
        return self.posts.all()

    def get_likes_given_no(self):
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value == 'Like':
                total_liked += 1
        return total_liked

    def get_like_recieved_no(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked

    __initial_first_name = None
    __initial_lats_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_lats_name = self.last_name

    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_lats_name or self.slug == "":

            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_randomcode()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)


STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)


class RelationshipManager(models.Manager):
    def invitations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs


class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

profiles/forms.py
from django import forms
from .models import Profile


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'email', 'bio', 'avatar', 'country',)


class SearchForFriends(forms.Form):
    query = forms.CharField()

profiles/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile, Relationship
from .forms import ProfileModelForm, SearchForFriends
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User


# Create your views here.
@login_required
def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True

    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm
    }

    return render(request, 'profiles/myprofile.html', context)


def invites_received_view(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invitations_received(profile)
    results = list(map(lambda x: x.sender, qs))
    is_empty = False
    if len(results) == 0:
        is_empty = True
    context = {'qs': results,
               'is_empty': is_empty, }

    return render(request, 'profiles/my_invites.html', context)


def accept_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('profiles:my-invites-view')


def reject_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('profiles:my-invites-view')


def invite_profile_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles_to_invite(user)

    context = {'qs': qs}

    return render(request, 'profiles/to_invite_list.html', context)


def profile_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles(user)

    context = {'qs': qs}

    return render(request, 'profiles/profile_list.html', context)


class ProfileDetailView(DetailView):
    model = Profile
    template_name = 'profiles/detail.html'

    def get_object(self, slug=None):
        slug = self.kwargs.get('slug')
        profile = Profile.objects.get(slug=slug)
        return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=str(self.request.user.username))
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)

        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['posts'] = self.get_object().get_all_authors_posts()
        context['len_posts'] = True if len(self.get_object().get_all_authors_posts()) > 0 else False
        return context


class ProfileListView(ListView):
    model = Profile
    template_name = 'profiles/profile_list.html'

    # context_object_name = 'qs'

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=str(self.request.user.username))
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)

        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True

        return context


def send_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')

        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile')


def remove_from_friends(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | Q(sender=receiver) & (Q(receiver=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile')


def search_from_friends(request):
    # if request.method == 'POST':
    #     username = request.POST.get('username')
    #     user = User.objects.filter(username__icontains=username).query
    #     return redirect(request.META.get('HTTP_REFERER'))
    # return redirect('profiles:my-profile')
    form = SearchForFriends()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForFriends(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Profile.objects.annotate(
                search=SearchForFriends('first_name', 'last_name', 'username'), ) \
                .filter(search=query)
    return render(request, 'profiles/profile_list.html',
                  {'form': form,
                   'query': query,
                   'results': results})

profiles/templates/profiles/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}

{% block title %}
    profile detail
{% endblock title %}

{% block content %}
    <div class="ui grid">
        <br>
        <br>
        <div class="row">
            <div class="col-sm-12 col-md-4" style="margin:2em;">
                    <div class="card">
                        <div class="container">
                            <img class="ui medium rounded image" style="margin-top:1em;" src="{{object.avatar.url}}">
                    <h1>{{object.user}}</h1>
                    <div class="ui vertical fluid menu">
                        <div class="item">
                            Posts
                            <div class="ui label">{{object.get_posts_no}}</div>
                        </div>
                        <div class="item">
                            Given Likes
                            <div class="ui label">{{object.get_likes_given_no}}</div>
                        </div>
                        <div class="item">
                            Likes
                            <div class="ui label">{{object.get_like_recieved_no}}</div>
                        </div>
                        <div class="item">
                            Total Friends
                            <div class="ui label">{{object.get_friends_no}}</div>
                        </div>
                    </div>
                        {% if object.user not in rel_receiver and object.user not in rel_sender %}
                                <form action="{% url 'profiles:send-invite' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="profile_pk" value="{{object.pk}}">

                                        <button type="submit" class="ui positive basic button mb-5  w-big">
                                            <i class="plus square icon"></i>
                                            Add to friends
                                        </button>
                                </form>
                        {% endif %}
                        {% if object.user in rel_receiver and request.user not in object.friends.all %}
                                <button class="ui disabled button mb-5  w-big">
                                    <i class="user icon"></i>
                                    Friend request is pending
                                </button>
                        {% endif %}

                        {% if  request.user in object.friends.all %}
                                <form action="{% url 'profiles:remove-friend' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="profile_pk" value="{{object.pk}}">
                                        <button type="submit" class="ui negative basic button mb-5  w-big">
                                            <i class="minus square icon"></i>
                                            Remove from friends
                                        </button>
                                </form>
                        {% endif %}
                        </div>
                    </div>
            </div>

            <div class="col-sm-12 col-md-7" style="margin-top:1em;">
                <br>
                {% if len_posts %}
                    {% for post in posts %}
                        <div class="segment ui fluid">
                          <h4>{{post.title}}</h4>
                          <blockquote>
                              {{post.content}}
                          </blockquote>
                        </div>
                    {% endfor %}
                {% else %}
                        <h5>{{object.user}} have no post..</h5>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}
</body>
</html>

profiles/templates/profiles/my_invites.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block title %}
    my invites
{% endblock title %}
{% block content %}
    {% if is_empty %}
        <h1>You don't have friend request </h1>
    {% endif %}
    {% for obj in qs %}
        <div class="segment card ">
            <div class="ui grid">
                <div class="row">
                    <div class="four wide column">
                        <img class="ui small circular image offset-2 mt-4" src="{{obj.avatar.url}}">
                    </div>
                    <div class="twelve wide column">
                        <h3 class="h3 mt-4">{{obj.user}}</h3>
                        <p class="text">{{obj.bio}}</p>
                        <a href="{{obj.get_absolute_url}}">
                            <button class="ui primary button w-big mb-5">
                                See profile
                            </button>
                        </a>
                        <div class="col-sm-12 col-md-12" style="display: inline-flex">
                            <div class="col-sm-12 col-md-6">
                                <form action="{% url 'profiles:accept-invite' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                                    <button type="submit" class="ui positive basic button  mb-5">
                                        <i class="smile icon"></i>
                                        Accept friend request
                                    </button>
                                </form>
                            </div>
                            <div class="col-sm-12 col-md-6">
                                <form action="{% url 'profiles:reject-invite' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                                    <button type="submit" class="ui negative basic button mb-5">
                                        <i class="close icon"></i>&nbsp;&nbsp;
                                        Reject invite &nbsp;&nbsp;
                                    </button>
                                </form>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}
</body>
</html>

profiles/templates/profiles/profile_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block title %}
        all profiles
    {% endblock title %}
    {% block content %}

    {% if is_empty %}
        <h1>Your profile list is empty</h1>
    {% endif %}
    {% for obj in object_list %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small rounded image" style="margin-left:2em;" src="{{obj.avatar.url}}">
                    </div>
                    <div class="thirteen wide column" style="margin-left:2em;">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href="{{obj.get_absolute_url}}">
                            <button class="ui positive basic button mb-5  w-big ">See profile</button>
                        </a>

                        <br>
                        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                            <form action="{% url 'profiles:send-invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{obj.pk}}">

                                    <button type="submit" class="ui positive basic button mb-5  w-big">
                                        <i class="plus square icon"></i>
                                        Add to friends
                                    </button>
                            </form>
                        {% endif %}
                        {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                            <button class="ui disabled button mb-5  w-big">
                                <i class="user icon"></i>
                                Friend request is pending
                            </button>
                        {% endif %}

                        {% if  request.user in obj.friends.all %}
                            <form action="{% url 'profiles:remove-friend' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                                    <button type="submit" class="ui negative basic button mb-5  w-big">
                                        <i class="minus square icon"></i>
                                        Remove from friends
                                    </button>
                            </form>
                        {% endif %}
                </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% endblock content %}
</body>
</html>

profiles/templates/profiles/to_invite_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block title %}
    invite friends
{% endblock title %}
{% block content %}
    <ul>
        {% for item in qs %}
            <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small rounded image" style="margin-left:2em;" src="{{item.avatar.url}}">
                    </div>
                    <div class="thirteen wide column" style="margin-left:2em;">
                        <h3>{{item.user}}</h3>
                        <p>{{item.bio}}</p>
                        <a href="{{item.get_absolute_url}}">
                            <button class="ui positive basic button mb-5  w-big ">See profile</button>
                        </a>

                        <br>
                        {% if item.user not in rel_receiver and item.user not in rel_sender %}
                            <form action="{% url 'profiles:send-invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{item.pk}}">

                                    <button type="submit" class="ui positive basic button mb-5  w-big">
                                        <i class="plus square icon"></i>
                                        Add to friends
                                    </button>
                            </form>
                        {% endif %}
                        {% if item.user in rel_receiver and request.user not in item.friends.all %}
                            <button class="ui disabled button mb-5  w-big">
                                <i class="user icon"></i>
                                Friend request is pending
                            </button>
                        {% endif %}

                        {% if  request.user in item.friends.all %}
                            <form action="{% url 'profiles:remove-friend' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{item.pk}}">
                                    <button type="submit" class="ui negative basic button mb-5  w-big">
                                        <i class="minus square icon"></i>
                                        Remove from friends
                                    </button>
                            </form>
                        {% endif %}
                </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </ul>
{% endblock content %}
</body>
</html>