posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, \
    like_unlike_post, PostDeleteView, PostUpdateView
from .feeds import LatestPostsFeed

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view,
    invites_received_view,
    invite_profile_list_view,
    ProfileListView,
    ProfileDetailView,
    send_invitation,
    remove_from_friends,
    accept_invitation,
    reject_invitation,
    search_from_friends,
)

app_name = 'profiles'
urlpatterns = [
    path('userprofile/', my_profile_view, name='my-profile'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('to-invite/', invite_profile_list_view, name='invite-profile-view'),
    path('send-invite/', send_invitation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('search-for-friends/', search_from_friends, name='search-for-friends'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),

    path('my-invite/accept/', accept_invitation, name='accept-invite'),
    path('my-invite/reject/', reject_invitation, name='reject-invite'),
]

soro_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .view import home_view

urlpatterns = [

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/main/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block title %}
    home
{% endblock title %}
{% block content %}
    {{hello}}
    <br>
    {{user}}
{% endblock content %}
{% block scripts %}
    <script>
        $(document).ready(function(){
            console.log('working')
        })
    </script>
{% endblock scripts %}
</body>
</html>

templates/main/navbar.html
<html>
    <head>
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-md  shadow" style="background-color: #CDB9B9;">
              <div class=" container">
                  <div class="navbar-brand ">
                      <a href="{% url 'posts:main-post-view' %}" class="item ">
                        <h3 class="brand" style="color: white">Soro</h3>
                    </a>
                  </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            {% if request.user.is_authenticated %}
                                  <li class="nav-item active ">
                                        <a class="nav-link " style="color: white" href="{% url 'posts:main-post-view' %}">Home <span class="sr-only">(current)</span></a>
                                  </li>
                                <li class="nav-item">
                                    <form class="form-inline" method="GET" action="profiles:search-for-friends">
                                        {% csrf_token %}
                                        <div class="input-group">
                                          <input type="text" class="form-control" placeholder="name of friend..."
                                                 aria-label="Find_friends" aria-describedby="basic-addon1"
                                                name="{{form.query.html_name}}" id="{{form.query.id_for_label">
                                        </div>
                                        <button type="submit" class="btn post_btn" style="background-color: white" >Search</button>
                                    </form>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle " style="color: white" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      Friends
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                      <a class="dropdown-item" href="{% url 'profiles:all-profiles-view' %}">All Profile</a>
                                      <a class="dropdown-item" href="{% url 'profiles:invite-profile-view' %}">Send Friend request</a>
                                      <a class="dropdown-item" href="{% url 'profiles:my-invites-view' %}">Receive Friend request</a>
                                    </div>
                                </li>
                                <li class="nav-item mr-auto dropdown">
                                    <a class="nav-link dropdown-toggle" style="color: white" href="#" id="navbarDropdownMenuLink1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      {{ request.user }}
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                                        <div class="nav-item dropdown">
                                            <a class="dropdown-item" href="{% url 'profiles:my-profile' %}">View Profile</a>
                                            <a class="dropdown-item" href="">Change password</a>
                                            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                                        </div>
                                    </div>
                                </li>
                            {% else %}
                                <li class="nav-item">Login</li>
                            {% endif %}
                        </ul>
                    </div>
              </div>
            </nav>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>